# Generated by Django 4.1.1 on 2022-09-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_bid_comment_remove_comments_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="highest_bid",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="item_categories", to="auctions.auctionlisting"
                    ),
                ),
            ],
        ),
    ]
