# Generated by Django 4.1.1 on 2022-09-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_auctionlisting_highest_bid_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="image",
            field=models.URLField(blank=True),
        ),
    ]
