# Generated by Django 4.1.1 on 2022-09-30 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_remove_auctionlisting_highest_bid_remove_bid_bids_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="listed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="watchers",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="watchers",
            field=models.ManyToManyField(
                related_name="watchers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
