# Generated by Django 4.1.1 on 2022-09-30 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_auctionlisting_buyer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winners",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
