# Generated by Django 4.1.1 on 2022-09-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_auctionlisting_buyer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
