# Generated by Django 4.1.1 on 2022-09-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_alter_auctionlisting_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="item",
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=9
            ),
        ),
    ]
