# Generated by Django 4.1.1 on 2022-10-02 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_alter_auctionlisting_item_alter_auctionlisting_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="watchers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
