# Generated by Django 4.1.1 on 2022-10-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_remove_auctionlisting_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=9
            ),
        ),
    ]
