# Generated by Django 4.1.1 on 2022-10-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0018_alter_bid_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(blank=True, help_text="Please Leave A Review"),
        ),
        migrations.DeleteModel(
            name="Watchlist",
        ),
    ]
